# Generated by Django 3.1.5 on 2021-01-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('fsqid', models.CharField(db_index=True, max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('venueid', models.CharField(db_index=True, max_length=24)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('city', models.CharField(db_index=True, max_length=25)),
                ('state', models.CharField(db_index=True, max_length=25)),
                ('country', models.CharField(db_index=True, max_length=25)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
