# Generated by Django 3.1.5 on 2021-01-23 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='flickrCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numTotal', models.IntegerField(db_index=True, default=0)),
                ('lastUpdated', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-lastUpdated'],
            },
        ),
    ]
