# Generated by Django 3.1.5 on 2021-01-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_flickrcache'),
    ]

    operations = [
        migrations.AddField(
            model_name='flickrcache',
            name='numPastYear',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
