# Generated by Django 3.1.5 on 2021-01-23 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_flickrcache_numpastyear'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flickrcache',
            options={'get_latest_by': ['-lastUpdated'], 'ordering': ['-lastUpdated']},
        ),
    ]
