# Generated by Django 3.1.5 on 2021-01-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210123_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flickrcache',
            name='lastUpdated',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
