# Generated by Django 3.1.5 on 2021-01-24 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210123_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
